name: Deploy CRUD

on:
  push:
    branches:
      - main

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Verify build output
        run: |
          echo "Contents of dist:"
          ls -la dist
          echo "Contents of project dist folder:"
          ls -la dist/angular-frontend

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: worksheet-build
          path: dist/angular-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: checkout-and-build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: worksheet-build
          path: build

      # Upload the built files to the EC2 instance
      - name: Upload build to EC2 via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "build/*"
          target: "/home/ubuntu/build-temp"

      # Deploy and restart nginx on EC2
      - name: Deploy and restart nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            echo "Deploying new build..."

            # ensure target dir exists
            sudo mkdir -p /var/www/html

            # remove old files and move new ones
            sudo rm -rf /var/www/html/*
            sudo mv /home/ubuntu/build-temp/* /var/www/html/

            # fix permissions
            sudo chown -R www-data:www-data /var/www/html

            # restart nginx
            sudo systemctl restart nginx

            echo "Deployment completed successfully!"
