name: Deploy CRUD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Verify dist contents
        run: |
          echo "dist folder:"
          ls -la dist
          echo "Angular build folder:"
          ls -la dist/angular-frontend

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/angular-frontend/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: build

      - name: Upload build to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "build/*"
          target: "/home/ubuntu/build-temp"

      - name: Deploy to nginx and restart
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            echo "Deploying Angular app to /var/www/html/ ..."

            # Ensure nginx web root exists
            sudo mkdir -p /var/www/html

            # Remove old files and move new build
            sudo rm -rf /var/www/html/*
            sudo mv /home/ubuntu/build-temp/* /var/www/html/

            # Set proper permissions
            sudo chown -R www-data:www-data /var/www/html

            # Restart nginx
            sudo systemctl restart nginx

            echo "✅ Deployment complete!"
